### PR TITLE
vendor: fix guard for face unlock

### PR DESCRIPTION
**Pull request by Ayushd70**

### CODE REVIEW

**Comment by neobuddy89** [comment]
PRODUCT_ARCH? where it is defined in android/build/make ?

**Comment by Ayushd70** [comment]
FYI, PRODUCT_ARCH is called through lineage_device.mk and TARGET_ARCH is called through BoardConfig.mk in device tree. 
Also for face unlock PRODUCT_ARCH is being checked as if now.

**Comment by gwolf2u** [comment]
TARGET_ARCH should be present in most BC

**Comment by Ayushd70** [comment]
> TARGET_ARCH should be present in most BC

But TARGET_ARCH doesn't get included in vendor calls and the file starts searching for it in lineage_device.mk which leads to a failure where as including PRODUCT_ARCH in lineage_device.mk makes the search successful leading to the inclusion.

**Pull request closed without merging**
