### PR TITLE
Quark mantainer + root app only enable by default

### PR DESCRIPTION
**Pull request by bhb27**
Quark mantainer + root app only enable by default

Root enable by default will prevent user wrong report of rooted app not working and prevent from flashing of supersu that is not fully working in all devices and can cause some other problem.

### CODE REVIEW

**Comment by alviteri** [comment]
absolutelly no ... root is disabled by default and only experienced users can enable it also everyone has the power to do it

**Comment by bhb27** [comment]
experienced users? everyone one that use a CM base ROM must have a minimum experience, and expect it to have root use xposed, root apps and etc related, the ROM comes with adaway a root only app, that doesn't make sense to me.



Root disable by default creates problem if they don't find Root is a problem they flash supersu creates another problem, every ROM that I released in the pass year it come with root enable by default, zero problem no user ever complain about root unless they wanna play those pokemon related games that another history already resolved.

This is just my input I know you guys may think I don't have yours experience not trying creates a discussion I understand you guys prefer no root by default.

I will close the pull and make one without the ROOT, and use the ROOT commit only on my ROM, I really prefer root on like I and many other have be doing for a long time in CM base ROM.

**Comment by alviteri** [comment]
I Will not change the rule Sorry .. if this is an inconvenient then I can remove this app from our releases

**Comment by bhb27** [comment]
No man if you remove I will add it locally on my vendor I really like the app, I and my user base just prefer the root thing on by default, I not complain I understand you sorry if sound like I trying to creates a problem I'm not.

thanks...

**Pull request closed without merging**
