### PR TITLE
crdroid: Fix and improve changelog script

### PR DESCRIPTION
**Pull request by iusmac**
**Main issue:** the build hangs on _recovery.img_ build with 0% CPU usage and 0% Disk usage.
<details>
    <summary>Demo</summary>

IMG_20220719_084802_681

</details>

**Investigation**
After digging, I found that the build is clogged by `changelog.sh` script called exactly in `build-recoveryimage` target:
**android/build/core/Makefile:2270**
```make
# $(1): output file
# $(2): optional kernel file
define build-recoveryimage-target
  $(hide) ./vendor/lineage/build/tools/changelog.sh $(TARGET_DEVICE)
  $(hide) mv $(PRODUCT_OUT)/Changelog.txt $(PRODUCT_OUT)/changelog_$(TARGET_DEVICE).txt
```
This shell script loops the `repo` command for N days.

Indeed, after manually killing the script and its childs, the build proceeds and further successfully completes:
<details>
    <summary>Demo</summary>

Screenshot from 2022-07-20 19-56-42

</details>

For unknown reason (to me), the `repo forall` command randomly hangs. If restarting the build ten times, only one will complete. Updating the _repo_ tool to the latest available version doesn't solve the issue.

**Solution**
Clearly, the `repo forall` command has some unhandled bugs in it. Also, it does a lot of "under the hood" work, which is pointless + slows down our changelog generation. All of this can be easily reworked using `repo list` command.

**What we got:**
- 3x faster changelog generation due to cached repos
- no more random build hangs due to `repo forall` command
- **Bonus fix:** I noticed that previously the commit order was not corresponding to the commit date. Code refactoring solved that. Compare the old `Changelog.txt` and the new `Changelog.txt` using `git show --format=fuller <commit-hash>`.

### CODE REVIEW

**Comment by xNombre** [comment]
Thanks god somebody fixed it eventually!

**Comment by gwolf2u** [comment]
this been tested?
my chaneglog not got generated

**Comment by neobuddy89** [comment]
Changelog not generating on lemonadep with or without this patch.

**Comment by iusmac** [comment]
Hm, execute the `changelog.sh` script manually from source directory. Maybe there's another unhandled bug in `repo` tool. For me everything is working fine, for both manual execution + execution during build.

**Pull request merged**
