### PR TITLE
Kernel: allow devices to use newer GCC

### PR DESCRIPTION
**Pull request by dhimanparas20**
Change-Id: I7ca23584c6479f300e38857707bec0bad1b94dad
Signed-off-by: Park Ju Hyung <qkrwngud825@gmail.com>

### CODE REVIEW

**Comment by xNombre** [comment]
Why do you need this? Cant you compile with latest clang as others?

**Comment by dhimanparas20** [comment]
> Why do you need this? Cant you compile with latest clang as others?

well i use LTO kernel which require this . If this goes missing , rom wont compile , AKA : Build error . 
alredy tested .

**Comment by xNombre** [comment]
> > Why do you need this? Cant you compile with latest clang as others?
> 
> well i use LTO kernel which require this . If this goes missing , rom wont compile , AKA : Build error .
> alredy tested .

Well, clang supports LTO. I think you should work on yr kernel as I was using lto in my kernel and had no problems at all. Also, Google is dropping GCC.

**Comment by dhimanparas20** [comment]
> > > Why do you need this? Cant you compile with latest clang as others?
> > 
> > 
> > well i use LTO kernel which require this . If this goes missing , rom wont compile , AKA : Build error .
> > alredy tested .
> 
> Well, clang supports LTO. I think you should work on yr kernel as I was using lto in my kernel and had no problems at all. Also, Google is dropping GCC.

oh i was unaware of it . Thanks for the info ill look into my kernel.

**Comment by ElectroPerf** [comment]
> > > Why do you need this? Cant you compile with latest clang as others?
> > 
> > 
> > well i use LTO kernel which require this . If this goes missing , rom wont compile , AKA : Build error .
> > alredy tested .
> 
> Well, clang supports LTO. I think you should work on yr kernel as I was using lto in my kernel and had no problems at all. Also, Google is dropping GCC.

Well LTO with clang is a scam. It has no difference as compared to non LTO kernels. It is even verified by the guy who first brought up clang LTO. So GCC only makes difference. And he is using latest GCC so doesnt matter.

See this :- https://t.me/EvaGCCSupport/15080

Also as long as this commit is not breaking other builds and also helping him to do his compilation so it doesnt really matters ig

**Comment by xNombre** [comment]
@ElectroPerf 
Early versions of clang were actually performing worse than gcc; however, now I find this whining inappropriate. Google switched to clang and is slowly tuning android build infrastructure to use more of its features. They wouldn't make such a big change without measurable effects. The digits may vary between different arches, certain kernel changes and... people you ask, nevertheless, saying LLVM LTO does nothing is a nonsense.

@dhimanparas20
After some digging, I've changed my mind. Some kernel hackers, like Sultan, still favor GCC. It means I am likely to add this flag to crDroid and give users more freedom to choose between compilers. :)

The only thing left is the actual commit code. It's merged wrongly. Force-push your branch with good-quality stuff.
PS. here is the original commit: https://github.com/AOSPA/android_vendor_pa/commit/e1d8d94df5f4c644c5e0c379e9dd2a121f829c27

**Comment by ElectroPerf** [comment]
> @ElectroPerf
> Early versions of clang were actually performing worse than gcc; however, now I find this whining inappropriate. Google switched to clang and is slowly tuning android build infrastructure to use more of its features. They wouldn't make such a big change without measurable effects. The digits may vary between different arches, certain kernel changes and... people you ask, nevertheless, saying LLVM LTO does nothing is a nonsense.
> 
> @dhimanparas20
> After some digging, I've changed my mind. Some kernel hackers, like Sultan, still favor GCC. It means I am likely to add this flag to crDroid and give users more freedom to choose between compilers. :)
> 
> The only thing left is the actual commit code. It's merged wrongly. Force-push your branch with good-quality stuff.
> PS. here is the original commit: [AOSPA/android_vendor_pa@e1d8d94](https://github.com/AOSPA/android_vendor_pa/commit/e1d8d94df5f4c644c5e0c379e9dd2a121f829c27)

Oo.. yea i see google moving towards clang.. and i also support it.. but i just felt it that clang LTO was going same as non LTO kernel or even worse.. Then i thought to try with GCC and Vaisakh bro said actually that GCC makes it out better with LTO. And he was right about it.. I mean in future such improvements might be done with clang.. but for time being, to utilise LTO properly we have to be with GCC.

**Comment by gwolf2u** [comment]
let's keep what we have for now

**Pull request closed without merging**
