### PR TITLE
Fix some common issues for maintainers

### PR DESCRIPTION
**Pull request by opensourcefreak**
I added some workarounds for issues that I have gotten pretty tired of fixing every time I sync the source.

### CODE REVIEW

**Comment by kondors1995** [comment]
just add all of this in your dt

**Comment by opensourcefreak** [comment]
I could add it to my it but it would be very discouraging for new porters to get an error spat in their face when first time they try to build something when we can easily fix it here.

**Comment by kondors1995** [comment]
still LTO one is not a good idea since we are losing quite a bit of perf

**Comment by opensourcefreak** [comment]
ThinLTO breaks build for all devices that use virtualization, among those all google pixel devices after the pixel 6. @Vikas-V2 probably removes those lines every time they build. Another alternative could be to add a flag in packages/modules/Virtualization so that ThinLTO is disabled when you inherit it, but I'm not sure if crDroid devs would merge any commits that messed around in there.

**Comment by dominator-prime** [comment]
> ThinLTO breaks build for all devices that use virtualization, among those all google pixel devices after the pixel 6. @Vikas-V2 probably removes those lines every time they build. Another alternative could be to add a flag in packages/modules/Virtualization so that ThinLTO is disabled when you inherit it, but I'm not sure if crDroid devs would merge any commits that messed around in there.

i don't have any issues now , i switched to pre-build google kernel  but yeah without prebuild i have to remove that line in initial days  that's just a pixel specific thing  no such issues in my qcom device

**Pull request closed without merging**
