### PR TITLE
 crDroid: add OPScreenRecorder [1/2]

### PR DESCRIPTION
**Pull request by gwolf2u**

### CODE REVIEW

**Comment by neobuddy89** [comment]
what to do with internal recording?

**Comment by gwolf2u** [comment]
Personally this works better I'd say with more options
Anyway, feel free to test and maybe add it as overlay option (like we have now anyway)?

**Comment by neobuddy89** [comment]
I meant this is being added under PRODUCT_PACKAGES
There is no way for device to disable it if it wants to use internal recording only.

**Comment by gwolf2u** [comment]
Ask maintainers also?
Those are the options...

**Comment by neobuddy89** [comment]
Will add this after March security clean up rebase.

**Comment by neobuddy89** [comment]
Tested. Doesn't show up in app drawer. Missing something?

**Comment by gwolf2u** [comment]
Is not in app drawer
Only tile

**Comment by gwolf2u** [comment]
Screenshot_20200301-083335

**Pull request closed without merging**
