### PR TITLE
crdroid: Fix device name generation for some devices

### PR DESCRIPTION
**Pull request by koron393**
* Fix for "including underscore in product name"
  like sony's Wi-Fi only devices.
  (scorpion_windy, karin_windy etc.)

Change-Id: I5ceed7a2a7f884079de95a32c488032c24457702

### CODE REVIEW

**Review by neobuddy89 — COMMENTED** [review]
Why not directly use TARGET_DEVICE?

@gwolf2u

**Comment by gwolf2u** [comment]
I'll see later tomorrow
In theory should be alright

**Comment by koron393** [comment]
Thanks for the answer.

I tested with "TARGET_DEVICE" and "PRODUCT_DEVICE".
But no luck.

**Comment by gwolf2u** [comment]
Try with
```
DEVICE=$(echo $TARGET_DEVICE)
```

**Comment by koron393** [comment]
Thanks.
I tried with your code

`DEVICE=$(echo $TARGET_DEVICE)`

and run "mka recoveryimage-nodeps"

> [100% 831/831] make recoveryimage-nodeps: ignoring dependencies
FAILED: recoveryimage-nodeps
/bin/bash -c "(./vendor/lineage/build/tools/changelog.sh ) && (mv out/target/product/scorpion_windy/Changelog.txt out/target/product/scorpion_windy/changelog_scorpion_windy.txt ) && (out/host/linux-x86/bin/mkbootimg --kernel   --ramdisk out/target/product/scorpion_windy/ramdisk-recovery.img --cmdline \"androidboot.hardware=qcom msm_rtb.filter=0x3b7 ehci-hcd.park=3 dwc3.maximum_speed=high dwc3_msm.prop_chg_detect=Y vmalloc=300M androidboot.selinux=permissive buildvariant=userdebug\" --base 0x00000000 --pagesize 2048 --os_version 11 --os_patch_level 2020-11-05 --ramdisk_offset 0x02000000 --tags_offset 0x01E00000 --output  out/target/product/scorpion_windy/recovery.img ) && (size=\$(for i in  out/target/product/scorpion_windy/recovery.img; do stat -c \"%s\" \"\$i\" | tr -d '\\n'; echo +; done; echo 0); total=\$(( \$( echo \"\$size\" ) )); printname=\$(echo -n \" out/target/product/scorpion_windy/recovery.img\" | tr \" \" +); maxsize=\$((   16777216-0)); if [ \"\$total\" -gt \"\$maxsize\" ]; then echo \"error: \$printname too large (\$total > \$maxsize)\"; false; elif [ \"\$total\" -gt \$((maxsize - 32768)) ]; then echo \"WARNING: \$printname approaching size limit (\$total now; limit \$maxsize)\"; fi )"
cp: out/target/product//system/etc/: No such file or directory
mv: bad 'out/target/product/scorpion_windy/Changelog.txt': No such file or directory
ninja: build stopped: subcommand failed.
05:05:40 ninja failed with: exit status 1


Next I tried with add "set" for debug

`set`
`DEVICE=$(echo $TARGET_DEVICE)`

and get this environment and get same error.

>ASAN_SYMBOLIZER_PATH=/home/koron/src/LOS/prebuilts/clang/host/linux-x86/llvm-binutils-stable/llvm-symbolizer
BASH=/bin/bash
BASHOPTS=cmdhist:complete_fullquote:extquote:force_fignore:hostcomplete:interactive_comments:progcomp:promptvars:sourcepath
BASH_ALIASES=()
BASH_ARGC=()
BASH_ARGV=()
BASH_CMDS=()
BASH_LINENO=([0]="0")
BASH_SOURCE=([0]="./vendor/lineage/build/tools/changelog.sh")
BASH_VERSINFO=([0]="4" [1]="4" [2]="23" [3]="1" [4]="release" [5]="x86_64-pc-linux-gnu")
BASH_VERSION='4.4.23(1)-release'
CCACHE_BASEDIR=/
CCACHE_COMPILERCHECK=content
CCACHE_CPP2=true
CCACHE_SLOPPINESS=time_macros,include_file_mtime,file_macro
Changelog=Changelog.txt
DIRSTACK=()
DIST_DIR=out/dist
EUID=1000
GROUPS=()
HOME=/home/koron
HOSTNAME=celica
HOSTTYPE=x86_64
IFS=$' \t\n'
JAVA_HOME=/home/koron/src/LOS/prebuilts/jdk/jdk11/linux-x86
LANG=C.UTF-8
LC_MESSAGES=C.UTF-8
MACHTYPE=x86_64-pc-linux-gnu
OPTERR=1
OPTIND=1
OSTYPE=linux-gnu
OUT_DIR=out
PATH=/home/koron/src/LOS/prebuilts/build-tools/path/linux-x86:/home/koron/src/LOS/out/.path
PIPESTATUS=([0]="0")
PPID=22211
PS4='+ '
PWD=/home/koron/src/LOS
PYTHONDONTWRITEBYTECODE=1
SHELL=/bin/bash
SHELLOPTS=braceexpand:hashall:interactive-comments
SHLVL=3
TARGET_BUILD_VARIANT=userdebug
TARGET_PRODUCT=lineage_scorpion_windy
TERM=dumb
TMPDIR=/home/koron/src/LOS/out/soong/.temp
UID=1000
USER=koron
_=


Probably $TARGET_DEVICE is not set to environment variables when executing changelog.sh.

**Review by gwolf2u — APPROVED** [review]

**Pull request merged**
