### PR TITLE
Add crdroid privapp-permissions

### PR DESCRIPTION
**Pull request by bdashore3**
"Caused marlin phones not to boot, these permissions fixed this issue"

Signed-off-by: kingbri <bdashore3@gmail.com>

### CODE REVIEW

**Comment by neobuddy89** [comment]
@gwolf2u please dont merge, need to review first.

**Comment by gwolf2u** [comment]
Tested locally
Doesn't affect us

**Comment by neobuddy89** [comment]
@gwolf2u every device will have "marlin" config unnecessarily. 
@bdashore3 can add via his DT.

**Comment by neobuddy89** [comment]
@bdashore3 can you share crash log? These permissions are already defined in actual packages.

**Comment by bdashore3** [comment]
I'll put in the old files and send you the missing permissions from the command line

**Pull request merged**
